### ISSUE TITLE
Example 'glyph-to-eps' doesn't work with latest version

### ISSUE THREAD

**Issue by tbrowder** [pdf-raku/Font-FreeType-raku#12]
FYI: In my modules with executable Raku progams I usually add a ./t or ./xt test for each. For example:

    $ cat ./t/test-examples.t
    use Test;
    use MyModule;

    lives-ok {
        raku -Ilib ./examples/eg1.raku
    }
 
That's very useful to me during development.

**Comment by tbrowder** [comment]
Looks like it needs:

    use FreeType::Raw:Defs;

to use the 'load-flags'.

**Comment by dwarring** [comment]
Fixed in latest release
