### ISSUE TITLE
Face methods returning metrics should be adjusted to reflect 'set-char-size' input

### ISSUE THREAD

**Issue by tbrowder** [pdf-raku/Font-FreeType-raku#16]

**Comment by dwarring** [comment]
The various Face metrics all currently return unscaled values. Some claim that they give scaled values (`ascender`, `descender`), or that they *will* be changed to produce scaled values (`underline-position`, `underline-thickness`). This behavior has been ported along with the Perl module and has never been scrutinized or corrected.

I'm planning to

- tidy up the documentation, for existing methods to state that they all return values in unscaled font units.
- introduce a new `scaled-metrics` method that returns a new `Font::FreeType::SizeMetrics` object.

This should be called after calling `set-char-size`, e.g.:

```raku
use Font::FreeType;
use Font::FreeType::SizeMetrics;
use Font::FreeType::Raw::Defs;

my Font::FreeType $ft .= new; # Load the BDF file.
my $vera = $ft.face: 't/fonts/Vera.ttf';
$vera.set-char-size(12,12,72,72);
my $scaled-metrics = $vera.scaled-metrics;
say $scaled-metrics.height;    # 5.25
say $scaled-metrics.descender; # -2.828125
say $scaled-metrics.bbox;      # [-2.203125 -2.828125 15.453125 11.140625]
```

**Comment by tbrowder** [comment]
David, I'm getting different results from the scaling. I'll try to be more specific tomorrow.

**Comment by tbrowder** [comment]
When I analyze a font file and extract the metrics ***without*** the new class, I do the following:

    my $ffil = "DejaVuSerif.ttf";
    my $ft   = Font::FreeType.new;
    my $font = $ft.face: $ffil, :load-flags(FT_LOAD_NO_HINTING);

    # calculate the scale factor
    my $sf = $size / $font.units-per-EM;

    # set the desired size
    $font.set-char-size: $size:
    # get an unadjusted font attribute
    my $ascender = $font.ascender;
    # adjust t for the desired size
    $ascender *= $sf;

Then use the new class to do the same thing

    my $fm = $font.scaled-metrics;

Compare the two:

    use Test;
    is $ascender, $fm.ascender;
    # OUTPUT: False;

**Comment by dwarring** [comment]
Thanks Tom, well spotted.

The metrics values are store to 22 binary places (6+ decimal places), but the calculations were incorrectly dividing twice, reducing the precision to 6 bits, which is less than 2 decimal places.

I've fixed the scaled font calculations and released Font::FreeType 0.4.8.

**Comment by tbrowder** [comment]
Great, I'll check it out.

**Comment by tbrowder** [comment]
In my testing it looks like the kern values don't get scaled with .set-char-size.

**Comment by dwarring** [comment]
No, I'll add a scaled `kerning` method to scaled metrics.

**Comment by dwarring** [comment]
Actually, I am finding that the `kerning` method does seem to scale:
```raku
use Test;
plan 2;
use Font::FreeType;
use Font::FreeType::Raw::Defs;
my $face = Font::FreeType.new.face: "t/fonts/Vera.ttf";

$face.set-char-size(12);
is $face.kerning('T', '.').x.round(.01), -1.42;

$face.set-char-size(24);
is $face.kerning('T', '.').x.round(.01), -2.84;
```

**Comment by tbrowder** [comment]
Thanks, David. I'll check my work again.

**Comment by tbrowder** [comment]
Sorry, my bad.
