### ISSUE TITLE
Using a list of glyph objects doesn't work as I would expect

### ISSUE THREAD

**Issue by tbrowder** [pdf-raku/Font-FreeType-raku#17]
I'm trying to do this (pseudo code):

    load a font file in a face object
    set the size for the font
    get a hash of Glyph objects keyed by the char
    set string width to zero
    for each char in a string of text
        get the glyph object from the hash
        get its attributes of interest
            width, height, bbox, etc.
            kern if there is a following char
        add the char width to the stringwidth

While watching the program run, I see no change in the attributes for any character. I see no difference in kerning between kern pairs.

Note it does appear the attributes have been scaled to the font size rather than the raw em size.

The program appears as [https://github.com/tbrowder/FontFactory/blob/master/dev/iterate-text.raku](https://github.com/tbrowder/FontFactory/blob/master/dev/iterate-text.raku).

**Comment by tbrowder** [comment]
Note that I can use the "for-all-*" subs but prefer doing it in the more conventional coding style I'm used to as referenced in the examples above.

**Comment by tbrowder** [comment]
I see now that the glyph is only valid on its call and dumped for the next glyph--bummer!

**Comment by dwarring** [comment]
Yes, unfortunately FreeType overwrites the current glyph each time a new glyph is loaded. It saves on allocations, but is a pain to use.
