### ISSUE TITLE
Glyph description should indicate that its metrics are scaled if the parent face has set-char-size()

### ISSUE THREAD

**Issue by tbrowder** [pdf-raku/Font-FreeType-raku#18]

**Comment by dwarring** [comment]
Hi Tom,
I've added some documentation and a code sample to the `Method` section.
I also found and corrected some bugs while I was looking at this, so you'll need to upgrade to Font::FreeType 0.4.9 to get a version  that works as documented. This module is supposed to return unscaled font units when `set-char-size` hasn't been called, but was erroneously dividing the value by 64.

**Comment by tbrowder** [comment]
Thanks.
