### ISSUE TITLE
Face description should state ALL its metrics and its glyph metrics are scaled after set-char-size() is called

### ISSUE THREAD

**Issue by tbrowder** [pdf-raku/Font-FreeType-raku#19]

**Comment by dwarring** [comment]
I've mentioned that glyph metrics are scaled and added some code to illustrate this to doco for the [set-char-size](https://pdf-raku.github.io/Font-FreeType-raku/Font/FreeType/Face#set-char-sizewidth-height-x-res-y-res) method.

I also fixed the `kerning` method to not divided by 64 when `mode` is `FT_KERNING_UNSCALED`, so FontFreeType 0.4.9 is needed to work as documented.

**Comment by tbrowder** [comment]
Much better, David. But just to be clear, are the kern metrics scaled when using 'set-char-size'? 

Is there a reason the face metrics can't be scaled at the same time as the glyphs are when using 'set-char-size'?

You might mention that only the width need be entered to 'set-char-size' and the height will be the same.

**Comment by dwarring** [comment]
Please see Font::FreeType release 0.50

Rather than changing `set-char-size()`, which could have an impact,  I've added a `set-font-size()` method that scales both the glyph and font metrics.

`set-char-size()` is now documented as being an 'older alternative' to `set-font-size()`.

**Comment by tbrowder** [comment]
That's great, David, and I'm converting my code now. 

However, in the Changes file, I see that it's new and replaces something, but I don't see that it mentions specifically what it replaces. 

Also, in the Face.rakumod file, the pod for set-font-size doesn't mention it also scales the base font metrics, i.e., that it replaces and augments the deprecated set-char-size method.

**Comment by tbrowder** [comment]
I have v0.5.0 installed and see .underline-thickness but **not** .underline-distance.

**Comment by dwarring** [comment]
Hi Tom, there is an .underline-position

**Comment by tbrowder** [comment]
"Ouch," he said, slapping his forehead, "I didn't see that, or I was focused on distance."

**Comment by tbrowder** [comment]
Thanks, David, sorry for the bandwidth waste. I only wish I could blame it on old age!
