### ISSUE TITLE
"make clean" is not removing libraries from "resources/libraries"

### ISSUE THREAD

**Issue by tbrowder** [pdf-raku/Font-FreeType-raku#20]
On Debian 11.

After manually cleaning, I got a build of a .so file that looks ok. However, then running "mi6 test" resulted in failures.

I can include a complete log of the test run if need bel

**Comment by dwarring** [comment]
It has done something. running `make clean` deleted `resources/libraries/libft6.so`, which resulted in #21. 

I'm trying to improve the LTA error messages there to make this more obvious.
