### ISSUE TITLE
“zef install Font::FreeType” fails on Debian 11

### ISSUE THREAD

**Issue by tbrowder** [pdf-raku/Font-FreeType-raku#21]
During installation, zef reports “Building [OK]” then starts testing and reports:

    # Failed test: ‘wrapper lib access’
    # at t/00-basic.t line 22
    # Type check failed in binding to parameter ‘$library’; expected IO::Path but got Slip (Empty) unable to access FreeType wrapper library; has it been built? (e.g. ‘zef build .) in block <unit> at t/00-basic.t line 22
    …
    ===> Testing [FAIL]…

Note I have the “libfreetype-dev” package installed on the host.

Also note, this occurs on one host but not another on which it installs fine.

**Comment by dwarring** [comment]
That error message is less than awesome, which I will try to fix. What's really going on is that `resources/libraries/libft6.so` hasn't been built by running `zef build .` or `raku Build.pm`

I'll also rename Build.pm -> Build.rakumod, like you did for Font::FreeType.

**Comment by dwarring** [comment]
Tom, If, you're working from git master, please update to see an improved error message. Otherwise, I'll just go ahead and upload to zef

**Comment by tbrowder** [comment]
I'll keep working on master. I'm going to close this issue because installation works fine on my Debian laptop.
