### ISSUE TITLE
Face method docs show "bbox" instead of "bounding-box" (but a "bbox" alias would be nice)

### ISSUE THREAD

**Issue by tbrowder** [pdf-raku/Font-FreeType-raku#23]

**Comment by dwarring** [comment]
Latest Font::FreeType 0.5.4 has `bbox` as a alias for `bounding-box`. Both return an object of type Font::FreeType::Box which is a 4 element array:  `x-min`, `y-min`, `x-max`, `y-max`.

This release also fixes scaled font `height` and `x-advance` scaling issues.

**Comment by tbrowder** [comment]
Thanks. Closing.
