### ISSUE TITLE
Make the default load flags suitable for outline, scalable fonts

### ISSUE THREAD

**Issue by tbrowder** [pdf-raku/Font-FreeType-raku#25]
I primarily want to typeset for PDF applications with scalable fonts. Consequently I would love to see the defaults set for the load flags like no auto hinting, no scaling, etc.

**Comment by dwarring** [comment]
Font::FreeType release 0.5.6 sets the default flags to `FT_LOAD_NO_SCALE +| FT_LOAD_NO_HINTING`.

**Comment by tbrowder** [comment]
Thanks, David!
