### ISSUE TITLE
OpenType fonts  are reported as format type "CFF"

### ISSUE THREAD

**Issue by tbrowder** [pdf-raku/Font-FreeType-raku#27]
I expected the format type to be "OpenType" but "CFF" was reported. I see that the font has a CFF table, but I don't understand why that would define its format when TrueType fonts are reported as TrueType.

**Comment by dwarring** [comment]
Yes, there's is actually a `*cff` format that also gets reported as "CFF" by the  underlying FreeType library.

OpenType `*otf` fonts theoretically have [two variants](https://learn.microsoft.com/en-us/typography/opentype/spec/otff#organization-of-an-opentype-font) that differ structurally `CFF` with Type1 outlines and `TT` with TrueType outlines, but I've never seen examples of the latter.

I'll have a look and see if there's some way of distinguishing simple CFF and OpenType CFF.

**Comment by dwarring** [comment]
Have changes as suggested. OpenType CFF now returns format `OpenType`. These fonts usually have extension `*.otf`.

Fix released with Font::FreeType  0.5.5

**Comment by tbrowder** [comment]
Thanks!
