### ISSUE TITLE
New $face requires a file path as a Str which is unexpected

### ISSUE THREAD

**Issue by tbrowder** [pdf-raku/Font-FreeType-raku#31]
That Str type requirement for a file path is not intuitive to a new user and could cause problems. 

Recommend either no type or use IO::Path as the user's entry. If the C code requires something else, that could be handled internally.

**Comment by dwarring** [comment]
Font::FreeType 0.5.10 has been released, which accepts an IO::Path argument.

**Comment by tbrowder** [comment]
Thanks!
