### ISSUE TITLE
Mention the C libfreetype6-dev library is a requirement

### ISSUE THREAD

**Issue by tbrowder** [pdf-raku/Font-FreeType-raku#9]

**Comment by dwarring** [comment]
Hi Tom. I think it is mentioned in the README.

Not also that the latest version of this module (0.4.5). should now run on Windows.

**Comment by tbrowder** [comment]
Good on the Windows fix!

And you're right, the dependency is shown.  But, IMHO, I would change the first line of the README to (in Rakudoc code)

    B<Font-FreeType> - Raku bindings to the B<FreeType> font library (version 2)

    See L<https://freetype.org>.

David, I continue to be greatly appreciative of your immense body of work for me and the rest of the Raku community. Thank you!

**Comment by dwarring** [comment]
Thanks @tbrowder, I've changed the first line of the README.
